sudo: required
services:
  - docker
env:
  global
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_8a8891480e43_key -iv $encrypted_8a8891480e43_iv -in marten.json.enc -out marten.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file marten.json
  - gcloud config set project multi-k8s-297817
  - gcloud config set compute/zone europe-north1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t martensoo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true martensoo/react-test npm test
 
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
     